name: Defensive Rating Automatic Scraper

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: run 
      run:
        python Scratch_Notebooks/DefensiveRating_Scraper.py
